# Generated by Django 3.1.5 on 2021-01-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210116_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimParams',
            new_name='SimParamsModel',
        ),
    ]
